### ISSUE TITLE
Can you add a license

### ISSUE THREAD

**Issue by tthiery** [FancyJS/FancyForm#5]
I personally favor a MIT or Apache2 ;)

ps: I like this library a lot. Never used it yet, but having a easy going code only form creation library is really nice. And maybe provide the source of the minified libraries if it is a public license.

**Comment by tthiery** [comment]
I just realized that within the source code header you offer a commercial license ... well ... then I have to create my own one. Will close this issue.

ps: License clarification on the Web / Github repo would be nice.

**Comment by MikeTatsky** [comment]
Thank you very much for interest in Fancy Form.
Please do not doubts on asking any questions.

**Comment by MikeTatsky** [comment]
About licence

One domain licence 5$
Any domains licences - 15$
One year support with all licences.
To prolong support on year - 5$
